name: push

on:
  push:
    branches: [ main ]
#   push:
#     tags:        
#       - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REGISTRY_NAMESPACE: markdumay
  IMAGE_NAME: trust

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push development images
#         run: ./dbm/dbm.sh dev build --push

      - name: Build and push production images
        run: ./dbm/dbm.sh prod build --push

#       - name: Set up Docker Trust
#         run: |
#           mkdir -p ~/.docker/trust/private
#           echo "$DOCKER_TRUST_SIGNER_KEY" > ~/.docker/trust/private/$DOCKER_TRUST_SIGNER_ID.key
#           echo "$DOCKER_TRUST_REPOSITORY_KEY" > ~/.docker/trust/private/$DOCKER_TRUST_REPOSITORY_ID.key
#           echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV
#           echo "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$DOCKER_TRUST_REPOSITORY_PASSPHASE" >> $GITHUB_ENV
#         env:
#           DOCKER_TRUST_SIGNER_ID: ${{ secrets.DOCKER_TRUST_SIGNER_ID }}
#           DOCKER_TRUST_SIGNER_KEY: ${{ secrets.DOCKER_TRUST_SIGNER_KEY }}
#           DOCKER_TRUST_REPOSITORY_ID: ${{ secrets.DOCKER_TRUST_REPOSITORY_ID }}
#           DOCKER_TRUST_REPOSITORY_KEY: ${{ secrets.DOCKER_TRUST_REPOSITORY_KEY }}
#           DOCKER_TRUST_REPOSITORY_PASSPHASE: ${{ secrets.DOCKER_TRUST_REPOSITORY_PASSPHASE }}

      - name: Set up Docker Trust
        run: |
          echo "$DOCKER_TRUST_SIGNER_KEY_PEM" > ~/github.key
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 notary
        env:
          DOCKER_TRUST_SIGNER_KEY_PEM: ${{ secrets.DOCKER_TRUST_SIGNER_KEY_PEM }}

      - name: Sign production images
        run: ./trust.sh ~/github.key markdumay/trust:0.2.4
