name: push

on:
  push:
    branches: [ main ]
#   push:
#     tags:        
#       - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REGISTRY_NAMESPACE: markdumay
  IMAGE_NAME: trust

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push development images
#         run: ./dbm/dbm.sh dev build --push

      - name: Build and push production images
        run: ./dbm/dbm.sh prod build --push

      - name: Set up Docker Trust
        run: |
          echo "${DOCKERHUB_SIGNER_KEY}" > ~/github.key
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 notary
        env:
          DOCKERHUB_SIGNER_KEY: ${{ secrets.DOCKERHUB_SIGNER_KEY }}

      - name: Sign production images
        run: ./trust.sh ~/github.key markdumay/trust:0.2.4
