name: push

on:
  push:
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Trust
        run: |
          mkdir -p ~/.docker/trust/private
          echo "${{ secrets.DOCKER_TRUST_SIGNER_KEY }}" > ~/.docker/trust/private/$DOCKER_TRUST_SIGNER_ID.key
          echo "${{ secrets.DOCKER_TRUST_REPOSITORY_KEY }}" > ~/.docker/trust/private/$DOCKER_TRUST_REPOSITORY_ID.key
          echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV
          echo "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=${{ secrets.DOCKER_TRUST_SIGNER_PASSPHASE }}" >> $GITHUB_ENV
        env:
          DOCKER_TRUST_SIGNER_ID: "${{ secrets.DOCKER_TRUST_SIGNER_ID }}"
          DOCKER_TRUST_REPOSITORY_ID: "${{ secrets.DOCKER_TRUST_REPOSITORY_ID }}"

      - name: Build and push development images
        run: ./dbm/dbm.sh dev build --push

      - name: Build and push production images
        run: ./dbm/dbm.sh prod build --push
